name: 'FireFlyCI'

description: 'Github Action for the command-line interface of the FireflyCI Firefly actions'

inputs:
  version:
    description: 'FireflyCI Version'
    required: false
    default: "latest"
  command:
    description: 'FireflyCI command to execute [post-apply, post-plan, redact]'
    required: true
  plan-file:
    description: 'Path to the plan file to scan'
    required: false
    default: ''
  workspace:
    description: 'Workspace identifier'
    required: false
    default: ''
  args:
    description: 'Additional arguments for the fireflyci executed command'
    default: ''

runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/firefly/fireflyci:v0.2.5'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - >-  
    /app/fireflyci ${{ inputs.command }}
    ${{ inputs.plan-file != '' && format('-f {0}', inputs.plan-file) || '' }}
    ${{ inputs.workspace != '' && format('-w {0}', inputs.workspace) || '' }}
    ${{ inputs.args }}
