name: 'FireflyCI'

description: 'GitHub action for the command-line interface of the FireflyCI Firefly actions'

inputs:
  version:
    description: 'FireflyCI Version'
    required: false
    default: "latest"
  command:
    description: 'FireflyCI command to execute [post-apply, post-plan]'
    required: true
  plan-output-file:
    description: 'Path to the plan output file'
    required: false
    default: ''
  plan-log-file:
    description: 'Path to the plan log file'
    required: false
    default: ''
  apply-log-file:
    description: 'Path to the apply log file'
    required: false
    default: ''
  workspace:
    description: 'Workspace identifier'
    required: true
    default: ''
  args:
    description: 'Additional arguments for the fireflyci executed command'
    default: ''

runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/firefly/fireflyci:v0.2.5'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - >-  
    cp -R /github/workspace/* / &&
    /app/fireflyci ${{ inputs.command }}
    ${{ inputs.plan-output-file != '' && format('-f {0}', inputs.plan-output-file) || '' }}
    ${{ inputs.plan-log-file != '' && format('-l {0}', inputs.plan-log-file) || '' }}
    ${{ inputs.apply-log-file != '' && format('-f {0}', inputs.apply-log-file) || '' }}
    ${{ inputs.workspace != '' && format('-w {0}', inputs.workspace) || '' }}
    ${{ inputs.args }}
